# Use the official Ubuntu 18.04 LTS as base image
FROM ubuntu:18.04

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt-get update && apt-get -y upgrade && apt-get -y install \
    apt-transport-https \
    ca-certificates \
    curl \
    git \
    libffi-dev \
    libssl-dev \
    libxml2-dev \
    libxslt1-dev \
    net-tools \
    python3-dev \
    python3-pip \
    python3-setuptools \
    python3-wheel \
    sshpass \
    sudo \
    vim

# Install Docker client
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
RUN echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
RUN apt-get update && apt-get -y install docker-ce-cli

# Install EVE-NG Community Edition
RUN curl -sL https://www.eve-ng.net/index.php/download-eve-ng-2/ | grep 'href.*eve-ng-community-edition' | grep -oP '(?<=href=")[^"]+' | xargs curl -LO
RUN tar xvfz eve-ng-community-edition-* -C /opt/

# Install Zabbix Server
RUN wget https://repo.zabbix.com/zabbix/5.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.4-1+ubuntu18.04_all.deb && \
    dpkg -i zabbix-release_5.4-1+ubuntu18.04_all.deb && \
    apt-get update && \
    apt-get -y install zabbix-server-mysql zabbix-frontend-php zabbix-apache-conf zabbix-agent

# Install NetBox
RUN git clone -b release https://github.com/netbox-community/netbox.git /opt/netbox
WORKDIR /opt/netbox
RUN pip3 install -r requirements.txt
RUN python3 manage.py migrate
RUN echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'admin')" | python3 manage.py shell

# Expose necessary ports
EXPOSE 80 443 8000 9000 10000 161/udp 162/udp

# Start services
CMD service zabbix-server start && service apache2 start && cd /opt/netbox && python3 manage.py runserver 0.0.0.0:8000 && cd /opt/unetlab && ./unl_wrapper -r -e && tail -f /dev/null
